name: test

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: ['10.x']
        include:
          - node-version: '10.x'
            mysql-variant: 'mysql'
            mysql-version: '5.7'
          - node-version: '10.x'
            mysql-variant: 'mysql'
            mysql-version: '8.0'
          - node-version: '10.x'
            mysql-variant: 'mariadb'
            mysql-version: '10.3'

    steps:
    - uses: actions/checkout@v1
    - name: Shutdown Ubuntu MySQL (SUDO)
      run: sudo service mysql stop
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up ${{ matrix.mysql-variant }} ${{ matrix.mysql-version }}
      uses: mirromutth/mysql-action@master
      with:
        mysql variant: ${{ matrix.mysql-variant }}
        mysql version: ${{ matrix.mysql-version }}
        mysql database: test
        mysql root password: ${{ secrets.DatabasePassword }}
    - name: npm install, build, and test
      run: |
        npm install
        npm run lint
        npm test -- --password=${{ secrets.DatabasePassword }}
      env:
        CI: true
